# Generated by Django 4.2.3 on 2023-08-13 19:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stories",
            name="excerpt",
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
