# Generated by Django 4.2.3 on 2023-08-13 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0002_stories_excerpt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stories",
            name="content",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="stories",
            name="excerpt",
            field=models.TextField(null=True),
        ),
    ]
